In [ ]:
import numpy as np

# Array 1 D
arr1 = np.arange(10)
print("Array 1D:", arr1)
print("Shape del Array 1D:", arr1.shape)
print("\n")

# Array 2 D
arr2 = np.arange(12).reshape(3, 4)
print("Array 2D:", arr2)
print("Shape del Array 2D:", arr2.shape)
print("\n")

# Matriz de ceros
zeros_matrix = np.zeros((2, 3))
print("Matriz de ceros:\n", zeros_matrix)
print("\n")

# Matriz de cualquier valor
value_matrix = np.full((2, 3), 7)
print("Matriz con valor 7:\n", value_matrix)
print("\n")

# Matriz de valores aleatorios
random_matrix = np.random.rand(2, 3)
print("Matriz de valores aleatorios:\n", random_matrix)
print("\n")

# Matriz de valores
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriz de valores:\n", arr3)
print("Tamaño de la Matriz de valores:", arr3.size)
print("Dimensiones de la Matriz de valores:", arr3.ndim)
print("Shape de la Matriz de valores:", arr3.shape)
print("\n")

Array 1D: [0 1 2 3 4 5 6 7 8 9]
Shape del Array 1D: (10,)


Array 2D: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape del Array 2D: (3, 4)


Matriz de ceros:
 [[0. 0. 0.]
 [0. 0. 0.]]


Matriz con valor 7:
 [[7 7 7]
 [7 7 7]]


Matriz de valores aleatorios:
 [[0.95410649 0.60007688 0.59016811]
 [0.19731723 0.6171808  0.39734935]]


Matriz de valores:
 [[1 2 3]
 [4 5 6]]
Tamaño de la Matriz de valores: 6
Dimensiones de la Matriz de valores: 2
Shape de la Matriz de valores: (2, 3)


Elemento en la posición (1,2): 60
Fila 0: [10 20 30]
Columna 1: [20 50 80]




In [24]:
# Indexación Básica
arr4 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Elemento en la posición (1,2):", arr4[1, 2])
print("Fila 0:", arr4[0, :])
print("Columna 1:", arr4[:, 1])
print("Ultimo elemento:", arr4[-1, -1])
print("\n")

Elemento en la posición (1,2): 60
Fila 0: [10 20 30]
Columna 1: [20 50 80]
Ultimo elemento: 90




In [ ]:
#Slising
arr5  = np.arange(1,13).reshape(3,4)
print("Array para slicing:\n", arr5)
print("\n")

arr6 = arr5[1:,1:3]
print("Slicing arr5[1:,1:3]:\n", arr6)
print("\n")

Array para slicing:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Slicing arr5[1:,1:]:
 [[ 6  7]
 [10 11]]




In [30]:
array_con_nan = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
print("Array con NaN:\n", array_con_nan)

sin_nan = np.nan_to_num(array_con_nan, nan=0)
print("Array sin NaN:\n", sin_nan)

Array con NaN:
 [[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
Array sin NaN:
 [[1. 2. 0.]
 [4. 0. 6.]
 [7. 8. 9.]]


In [32]:
arr7 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array original:\n", arr7)

arr_sin_menor_5 = np.where(arr7 < 5, 5, arr7)
print("Array con valores menores a 5 reemplazados por 5:\n", arr_sin_menor_5)

Array original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array con valores menores a 5 reemplazados por 5:
 [[5 5 5]
 [5 5 6]
 [7 8 9]]
